create table if not exists public.consumo_diario (
  id bigint generated by default as identity primary key,
  dia_sigla text not null,
  ordem smallint not null,
  kwh integer not null check (kwh >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.eventos_escola (
  id bigint generated by default as identity primary key,
  data_evento date not null,
  descricao text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.qualidade_ar (
  id bigint generated by default as identity primary key,
  sala integer not null check (sala between 317 and 321),
  co2 integer not null check (co2 > 0),
  pm25 integer not null check (pm25 >= 0),
  collected_at timestamptz not null default now()
);

alter table public.consumo_diario enable row level security;
alter table public.eventos_escola enable row level security;
alter table public.qualidade_ar enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'consumo_diario' and policyname = 'consumo_diario_select_public'
  ) then
    create policy consumo_diario_select_public
      on public.consumo_diario
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'eventos_escola' and policyname = 'eventos_escola_select_public'
  ) then
    create policy eventos_escola_select_public
      on public.eventos_escola
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'qualidade_ar' and policyname = 'qualidade_ar_select_public'
  ) then
    create policy qualidade_ar_select_public
      on public.qualidade_ar
      for select
      to anon
      using (true);
  end if;
end
$$;
